---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    name: meshnet
- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: topologies.networkop.co.uk
  spec:
    group: networkop.co.uk
    versions:
    - name: v1beta1
      served: true
      storage: true
    scope: Namespaced
    subresources:
      status: {}
    names:
      plural: topologies
      singular: topology
      kind: Topology
      shortNames:
      - topo
    validation:
      openAPIV3Schema:
        properties:
          status:
            properties:
              skipped:
                description: 'List of pods that are skipped by local pod'
                type: array
                items:
                  type: string
                  description: 'peer pod name'
              src_ip:
                description: 'Source IP of the POD'
                type: string
              net_ns:
                description: 'Network namespace of the POD'
                type: string
          spec:
            properties:
              links:
                type: array
                items:
                  type: object
                  description: 'A complete definition of a p2p link'
                  required: ["uid", "peer_pod", "local_intf", "peer_intf"]
                  properties:
                    uid:
                      description: 'Unique identified of a p2p link'
                      type: integer
                    peer_pod:
                      description: 'Name of the peer pod'
                      type: string
                    local_intf:
                      description: 'Local interface name'
                      type: string
                    peer_intf:
                      description: 'Peer interface name'
                      type: string
                    peer_ip:
                      description: '(Optional) Local IP address'
                      type: string
                    local_ip:
                      description: '(Optional) Peer IP address'
                      type: string
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: meshnet
    namespace: meshnet
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: meshnet-clusterrole
  rules:
  - apiGroups:
    - "networkop.co.uk"
    resources:
    - topologies
    verbs: ["*"]
  - apiGroups:
    - "networkop.co.uk"
    resources:
    - topologies/status
    verbs: ["*"]
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: meshnet-clusterrolebinding
  roleRef:
    kind: ClusterRole
    name: meshnet-clusterrole
    apiGroup: rbac.authorization.k8s.io
  subjects:
  - kind: ServiceAccount
    name: meshnet
    namespace: meshnet
- apiVersion: apps/v1
  kind: DaemonSet
  metadata:
    name: meshnet
    namespace: meshnet
    labels:
      k8s-app: meshnet
  spec:
    selector:
      matchLabels:
        name: meshnet
    template:
      metadata:
        labels:
          name: meshnet
      spec:
        hostNetwork: true
        hostPID: true
        hostIPC: true
        serviceAccountName: meshnet
        nodeSelector:
          beta.kubernetes.io/arch: amd64
        tolerations:
        - operator: Exists
          effect: NoSchedule
        containers:
        - name: meshnet
          securityContext:
            privileged: true
          image: networkop/meshnet:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
          - name: cni-cfg
            mountPath: /etc/cni/net.d
          - name: cni-bin
            mountPath: /opt/cni/bin
          - name: var-run-netns
            mountPath: /var/run/netns
            mountPropagation: Bidirectional
        terminationGracePeriodSeconds: 0
        volumes:
        - name: cni-bin
          hostPath:
            path: /opt/cni/bin
        - name: cni-cfg
          hostPath:
            path: /etc/cni/net.d
        - name: var-run-netns
          hostPath:
            path: /var/run/netns