name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build latest meshnet 
      run: make build
    - name: Build a local test environment
      run: make local
    - name: Upload the new meshnet image
      run: make upload
    - name: Install meshnet 
      run: make ci-install
    - name: Wait for meshnet to install
      run: make wait-for-meshnet
    - name: Run tests
      run: make test
    - name: Build final version
      run: make build
    - name: Docker login
      run: echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PWD }}
    - name: Release final version
      run: |
        make build
        make release
